services:
  flask-app:
    build: .
    container_name: flask-devops-app
    ports:
      - "5000:5000"
    environment:
      APP_NAME: "DevOps CI/CD Flask App"
      ENV: "production"
    restart: always
